Make test code use the correct signed types
There were a number of comparisons in the tests that were comparing
signed ints to unsigned ints.  This lead to compiler errors in some
cases.

../../../../../../workspace/sources/phosphor-snmp/test/test_error_notification.cpp:35:5:
required from here
| /usr/src/gtest/include/gtest/gtest.h:1545:11:
error: comparison of integer expressions of different signedness: 'const
int' and 'const unsigned int' [-Werror=sign-compare]
|   if (lhs == rhs) {

This commit fixes it.

Tested: Code compiles, unit test changes only.

Signed-off-by: Ed Tanous <edtanous@google.com>
Change-Id: Ib6dd2afced3672ec1f7096ade07b36d53049cf1a